FROM tensorflow/tensorflow:1.5.0-py3

RUN pip install svgwrite pylint tqdm

RUN pip install --upgrade \
	https://github.com/mind/wheels/releases/download/tf1.5-cpu/tensorflow-1.5.0-cp35-cp35m-linux_x86_64.whl
